#//////////////////////////////////////////////////////////////////////////////
#   -- MAGMA (version 2.0.2) --
#      Univ. of Tennessee, Knoxville
#      Univ. of California, Berkeley
#      Univ. of Colorado, Denver
#      @date May 2016
#//////////////////////////////////////////////////////////////////////////////

# push previous directory
dir_stack := $(dir_stack) $(cdir)
cdir      := interface_cuda
# ----------------------------------------------------------------------


# alphabetic order by base name (ignoring precision)
libmagma_zsrc += \
	$(cdir)/blas_z_v1.cpp	\
	$(cdir)/blas_z_v2.cpp	\

libmagma_src += \
	$(cdir)/alloc.cpp	\
	$(cdir)/error.cpp	\
	$(cdir)/interface.cpp	\
	$(cdir)/copy_v1.cpp	\
	$(cdir)/copy_v2.cpp	\


# ----------------------------------------------------------------------
# pop first directory
cdir      := $(firstword $(dir_stack))
dir_stack := $(wordlist 2, $(words $(dir_stack)), $(dir_stack))
