!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!  This file is AUTOMATICALLY GENERATED by:
!!  ../tools/fortran_wrappers.pl ../include/magmablas_d.i
!!  Do not edit.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

module magmablas_dfortran

use magma_param

implicit none

!---- Fortran interfaces to MAGMA subroutines ----
interface

subroutine magmablasf_dtranspose_inplace( n, dA, ldda )
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
end subroutine magmablasf_dtranspose_inplace

subroutine magmablasf_dtranspose( m, n, dA, ldda, dAT, lddat )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dAT
    integer          :: lddat
end subroutine magmablasf_dtranspose

subroutine magmablasf_dgetmatrix_transpose( m, n, dAT, ldda, hA, lda, dwork, lddwork, nb  &
        )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dAT
    integer          :: ldda
    double precision :: hA(*)
    integer          :: lda
    magma_devptr_t   :: dwork
    integer          :: lddwork
    integer          :: nb
end subroutine magmablasf_dgetmatrix_transpose

subroutine magmablasf_dsetmatrix_transpose( m, n, hA, lda, dAT, ldda, dwork, lddwork, nb  &
        )
    integer          :: m
    integer          :: n
    double precision :: hA(*)
    integer          :: lda
    magma_devptr_t   :: dAT
    integer          :: ldda
    magma_devptr_t   :: dwork
    integer          :: lddwork
    integer          :: nb
end subroutine magmablasf_dsetmatrix_transpose

subroutine magmablasf_dprbt( n, dA, ldda, du, dv )
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: du
    magma_devptr_t   :: dv
end subroutine magmablasf_dprbt

subroutine magmablasf_dprbt_mv( n, dv, db )
    integer          :: n
    magma_devptr_t   :: dv
    magma_devptr_t   :: db
end subroutine magmablasf_dprbt_mv

subroutine magmablasf_dprbt_mtv( n, du, db )
    integer          :: n
    magma_devptr_t   :: du
    magma_devptr_t   :: db
end subroutine magmablasf_dprbt_mtv

subroutine magmablasf_dgeadd( m, n, alpha, dA, ldda, dB, lddb )
    integer          :: m
    integer          :: n
    double precision :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
end subroutine magmablasf_dgeadd

subroutine magmablasf_dlacpy( uplo, m, n, dA, ldda, dB, lddb )
    character        :: uplo
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
end subroutine magmablasf_dlacpy

subroutine magmablasf_dlacpy_cnjg( n, dA1, lda1, dA2, lda2 )
    integer          :: n
    magma_devptr_t   :: dA1
    integer          :: lda1
    magma_devptr_t   :: dA2
    integer          :: lda2
end subroutine magmablasf_dlacpy_cnjg

subroutine magmablasf_dlacpy_sym_in( uplo, m, n, rows, perm, dA, ldda, dB, lddb )
    character        :: uplo
    integer          :: m
    integer          :: n
    integer          :: rows(*)
    integer          :: perm(*)
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
end subroutine magmablasf_dlacpy_sym_in

subroutine magmablasf_dlacpy_sym_out( uplo, m, n, rows, perm, dA, ldda, dB, lddb )
    character        :: uplo
    integer          :: m
    integer          :: n
    integer          :: rows(*)
    integer          :: perm(*)
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
end subroutine magmablasf_dlacpy_sym_out

subroutine magmablasf_dlascl( type, kl, ku, cfrom, cto, m, n, dA, ldda, info )
    character        :: type
    integer          :: kl
    integer          :: ku
    double precision :: cfrom
    double precision :: cto
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    integer          :: info
end subroutine magmablasf_dlascl

subroutine magmablasf_dlascl_2x2( type, m, dW, lddw, dA, ldda, info )
    character        :: type
    integer          :: m
    magma_devptr_t   :: dW
    integer          :: lddw
    magma_devptr_t   :: dA
    integer          :: ldda
    integer          :: info
end subroutine magmablasf_dlascl_2x2

subroutine magmablasf_dlascl2( type, m, n, dD, dA, ldda, info )
    character        :: type
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dD
    magma_devptr_t   :: dA
    integer          :: ldda
    integer          :: info
end subroutine magmablasf_dlascl2

subroutine magmablasf_dlascl_diag( type, m, n, dD, lddd, dA, ldda, info )
    character        :: type
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dD
    integer          :: lddd
    magma_devptr_t   :: dA
    integer          :: ldda
    integer          :: info
end subroutine magmablasf_dlascl_diag

subroutine magmablasf_dlaset( uplo, m, n, offdiag, diag, dA, ldda )
    character        :: uplo
    integer          :: m
    integer          :: n
    double precision :: offdiag
    double precision :: diag
    magma_devptr_t   :: dA
    integer          :: ldda
end subroutine magmablasf_dlaset

subroutine magmablasf_dlaset_band( uplo, m, n, k, offdiag, diag, dA, ldda )
    character        :: uplo
    integer          :: m
    integer          :: n
    integer          :: k
    double precision :: offdiag
    double precision :: diag
    magma_devptr_t   :: dA
    integer          :: ldda
end subroutine magmablasf_dlaset_band

subroutine magmablasf_dlaswp( n, dAT, ldda, k1, k2, ipiv, inci )
    integer          :: n
    magma_devptr_t   :: dAT
    integer          :: ldda
    integer          :: k1
    integer          :: k2
    integer          :: ipiv(*)
    integer          :: inci
end subroutine magmablasf_dlaswp

subroutine magmablasf_dlaswp2( n, dAT, ldda, k1, k2, d_ipiv, inci )
    integer          :: n
    magma_devptr_t   :: dAT
    integer          :: ldda
    integer          :: k1
    integer          :: k2
    magma_devptr_t   :: d_ipiv
    integer          :: inci
end subroutine magmablasf_dlaswp2

subroutine magmablasf_dlaswp_sym( n, dA, ldda, k1, k2, ipiv, inci )
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    integer          :: k1
    integer          :: k2
    integer          :: ipiv(*)
    integer          :: inci
end subroutine magmablasf_dlaswp_sym

subroutine magmablasf_dlaswpx( n, dA, ldx, ldy, k1, k2, ipiv, inci )
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldx
    integer          :: ldy
    integer          :: k1
    integer          :: k2
    integer          :: ipiv(*)
    integer          :: inci
end subroutine magmablasf_dlaswpx

subroutine magmablasf_dsymmetrize( uplo, m, dA, ldda )
    character        :: uplo
    integer          :: m
    magma_devptr_t   :: dA
    integer          :: ldda
end subroutine magmablasf_dsymmetrize

subroutine magmablasf_dsymmetrize_tiles( uplo, m, dA, ldda, ntile, mstride, nstride )
    character        :: uplo
    integer          :: m
    magma_devptr_t   :: dA
    integer          :: ldda
    integer          :: ntile
    integer          :: mstride
    integer          :: nstride
end subroutine magmablasf_dsymmetrize_tiles

subroutine magmablasf_dtrtri_diag( uplo, diag, n, dA, ldda, d_dinvA )
    character        :: uplo
    character        :: diag
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: d_dinvA
end subroutine magmablasf_dtrtri_diag

subroutine magmablasf_dnrm2_adjust( k, dxnorm, dc )
    integer          :: k
    magma_devptr_t   :: dxnorm
    magma_devptr_t   :: dc
end subroutine magmablasf_dnrm2_adjust

subroutine magmablasf_dnrm2_check( m, n, dA, ldda, dxnorm, dlsticc )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dxnorm
    magma_devptr_t   :: dlsticc
end subroutine magmablasf_dnrm2_check

subroutine magmablasf_dnrm2_cols( m, n, dA, ldda, dxnorm )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dxnorm
end subroutine magmablasf_dnrm2_cols

subroutine magmablasf_dnrm2_row_check_adjust( k, tol, dxnorm, dxnorm2, dC, lddc, dlsticc  &
        )
    integer          :: k
    double precision :: tol
    magma_devptr_t   :: dxnorm
    magma_devptr_t   :: dxnorm2
    magma_devptr_t   :: dC
    integer          :: lddc
    magma_devptr_t   :: dlsticc
end subroutine magmablasf_dnrm2_row_check_adjust

subroutine magmaf_dlarfbx_gpu( m, k, V, ldv, dT, ldt, c, dwork )
    integer          :: m
    integer          :: k
    magma_devptr_t   :: V
    integer          :: ldv
    magma_devptr_t   :: dT
    integer          :: ldt
    magma_devptr_t   :: c
    magma_devptr_t   :: dwork
end subroutine magmaf_dlarfbx_gpu

subroutine magmaf_dlarfgtx_gpu( n, dx0, dx, dtau, dxnorm, dA, iter, V, ldv, T, ldt, dwork  &
        )
    integer          :: n
    magma_devptr_t   :: dx0
    magma_devptr_t   :: dx
    magma_devptr_t   :: dtau
    magma_devptr_t   :: dxnorm
    magma_devptr_t   :: dA
    integer          :: iter
    magma_devptr_t   :: V
    integer          :: ldv
    magma_devptr_t   :: T
    integer          :: ldt
    magma_devptr_t   :: dwork
end subroutine magmaf_dlarfgtx_gpu

subroutine magmaf_dlarfgx_gpu( n, dx0, dx, dtau, dxnorm, dA, iter )
    integer          :: n
    magma_devptr_t   :: dx0
    magma_devptr_t   :: dx
    magma_devptr_t   :: dtau
    magma_devptr_t   :: dxnorm
    magma_devptr_t   :: dA
    integer          :: iter
end subroutine magmaf_dlarfgx_gpu

subroutine magmaf_dlarfx_gpu( m, n, v, tau, C, ldc, xnorm, dT, iter, work )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: v
    magma_devptr_t   :: tau
    magma_devptr_t   :: C
    integer          :: ldc
    magma_devptr_t   :: xnorm
    magma_devptr_t   :: dT
    integer          :: iter
    magma_devptr_t   :: work
end subroutine magmaf_dlarfx_gpu

subroutine magmablasf_daxpycp( m, dr, dx, db )
    integer          :: m
    magma_devptr_t   :: dr
    magma_devptr_t   :: dx
    magma_devptr_t   :: db
end subroutine magmablasf_daxpycp

subroutine magmablasf_dswap( n, dx, incx, dy, incy )
    integer          :: n
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: dy
    integer          :: incy
end subroutine magmablasf_dswap

subroutine magmablasf_dswapblk( order, n, dA, ldda, dB, lddb, i1, i2, ipiv, inci, offset  &
        )
    character        :: order
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    integer          :: i1
    integer          :: i2
    integer          :: ipiv(*)
    integer          :: inci
    integer          :: offset
end subroutine magmablasf_dswapblk

subroutine magmablasf_dswapdblk( n, nb, dA, ldda, inca, dB, lddb, incb )
    integer          :: n
    integer          :: nb
    magma_devptr_t   :: dA
    integer          :: ldda
    integer          :: inca
    magma_devptr_t   :: dB
    integer          :: lddb
    integer          :: incb
end subroutine magmablasf_dswapdblk

subroutine magmablasf_dtrsv( uplo, transA, diag, n, dA, ldda, db, incb, queue )
    character        :: uplo
    character        :: transA
    character        :: diag
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: db
    integer          :: incb
    integer          :: queue
end subroutine magmablasf_dtrsv

subroutine magmablasf_dtrsv_outofplace( uplo, transA, diag, n, dA, ldda, db, incb, dx,  &
        queue, flag )
    character        :: uplo
    character        :: transA
    character        :: diag
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: db
    integer          :: incb
    magma_devptr_t   :: dx
    integer          :: queue
    integer          :: flag
end subroutine magmablasf_dtrsv_outofplace

subroutine magmablasf_dgemv_q( trans, m, n, alpha, dA, ldda, dx, incx, beta, dy, incy,  &
        queue )
    character        :: trans
    integer          :: m
    integer          :: n
    double precision :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dx
    integer          :: incx
    double precision :: beta
    magma_devptr_t   :: dy
    integer          :: incy
    integer          :: queue
end subroutine magmablasf_dgemv_q

subroutine magmablasf_dgemv( trans, m, n, alpha, dA, ldda, dx, incx, beta, dy, incy )
    character        :: trans
    integer          :: m
    integer          :: n
    double precision :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dx
    integer          :: incx
    double precision :: beta
    magma_devptr_t   :: dy
    integer          :: incy
end subroutine magmablasf_dgemv

subroutine magmablasf_dgemv_conjv( m, n, alpha, dA, ldda, dx, incx, beta, dy, incy )
    integer          :: m
    integer          :: n
    double precision :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dx
    integer          :: incx
    double precision :: beta
    magma_devptr_t   :: dy
    integer          :: incy
end subroutine magmablasf_dgemv_conjv

subroutine magmablasf_dsymv( uplo, n, alpha, dA, ldda, dx, incx, beta, dy, incy )
    character        :: uplo
    integer          :: n
    double precision :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dx
    integer          :: incx
    double precision :: beta
    magma_devptr_t   :: dy
    integer          :: incy
end subroutine magmablasf_dsymv

subroutine magmablasf_dsymv_work( uplo, n, alpha, dA, ldda, dx, incx, beta, dy, incy,  &
        dwork, lwork, queue )
    character        :: uplo
    integer          :: n
    double precision :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dx
    integer          :: incx
    double precision :: beta
    magma_devptr_t   :: dy
    integer          :: incy
    magma_devptr_t   :: dwork
    integer          :: lwork
    integer          :: queue
end subroutine magmablasf_dsymv_work

subroutine magmablasf_dgemm( transA, transB, m, n, k, alpha, dA, ldda, dB, lddb, beta,  &
        dC, lddc )
    character        :: transA
    character        :: transB
    integer          :: m
    integer          :: n
    integer          :: k
    double precision :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    double precision :: beta
    magma_devptr_t   :: dC
    integer          :: lddc
end subroutine magmablasf_dgemm

subroutine magmablasf_dgemm_reduce( m, n, k, alpha, dA, ldda, dB, lddb, beta, dC, lddc )
    integer          :: m
    integer          :: n
    integer          :: k
    double precision :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    double precision :: beta
    magma_devptr_t   :: dC
    integer          :: lddc
end subroutine magmablasf_dgemm_reduce

subroutine magmablasf_dtrsm( side, uplo, transA, diag, m, n, alpha, dA, ldda, dB, lddb )
    character        :: side
    character        :: uplo
    character        :: transA
    character        :: diag
    integer          :: m
    integer          :: n
    double precision :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
end subroutine magmablasf_dtrsm

subroutine magmablasf_dtrsm_outofplace( side, uplo, transA, diag, m, n, alpha, dA, ldda,  &
        dB, lddb, dX, lddx, flag, d_dinvA, dinvA_length )
    character        :: side
    character        :: uplo
    character        :: transA
    character        :: diag
    integer          :: m
    integer          :: n
    double precision :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    magma_devptr_t   :: dX
    integer          :: lddx
    integer          :: flag
    magma_devptr_t   :: d_dinvA
    integer          :: dinvA_length
end subroutine magmablasf_dtrsm_outofplace

subroutine magmablasf_dtrsm_work( side, uplo, transA, diag, m, n, alpha, dA, ldda, dB,  &
        lddb, dX, lddx, flag, d_dinvA, dinvA_length )
    character        :: side
    character        :: uplo
    character        :: transA
    character        :: diag
    integer          :: m
    integer          :: n
    double precision :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    magma_devptr_t   :: dX
    integer          :: lddx
    integer          :: flag
    magma_devptr_t   :: d_dinvA
    integer          :: dinvA_length
end subroutine magmablasf_dtrsm_work

subroutine magmaf_dsetvector( n, hx_src, incx, dy_dst, incy )
    integer          :: n
    double precision :: hx_src(*)
    integer          :: incx
    magma_devptr_t   :: dy_dst
    integer          :: incy
end subroutine magmaf_dsetvector

subroutine magmaf_dgetvector( n, dx_src, incx, hy_dst, incy )
    integer          :: n
    magma_devptr_t   :: dx_src
    integer          :: incx
    double precision :: hy_dst(*)
    integer          :: incy
end subroutine magmaf_dgetvector

subroutine magmaf_dcopyvector( n, dx_src, incx, dy_dst, incy )
    integer          :: n
    magma_devptr_t   :: dx_src
    integer          :: incx
    magma_devptr_t   :: dy_dst
    integer          :: incy
end subroutine magmaf_dcopyvector

subroutine magmaf_dsetvector_async( n, hx_src, incx, dy_dst, incy, queue )
    integer          :: n
    double precision :: hx_src(*)
    integer          :: incx
    magma_devptr_t   :: dy_dst
    integer          :: incy
    integer          :: queue
end subroutine magmaf_dsetvector_async

subroutine magmaf_dgetvector_async( n, dx_src, incx, hy_dst, incy, queue )
    integer          :: n
    magma_devptr_t   :: dx_src
    integer          :: incx
    double precision :: hy_dst(*)
    integer          :: incy
    integer          :: queue
end subroutine magmaf_dgetvector_async

subroutine magmaf_dcopyvector_async( n, dx_src, incx, dy_dst, incy, queue )
    integer          :: n
    magma_devptr_t   :: dx_src
    integer          :: incx
    magma_devptr_t   :: dy_dst
    integer          :: incy
    integer          :: queue
end subroutine magmaf_dcopyvector_async

subroutine magmaf_dsetmatrix( m, n, hA_src, ldha, dB_dst, lddb )
    integer          :: m
    integer          :: n
    double precision :: hA_src(*)
    integer          :: ldha
    magma_devptr_t   :: dB_dst
    integer          :: lddb
end subroutine magmaf_dsetmatrix

subroutine magmaf_dgetmatrix( m, n, dA_src, ldda, hB_dst, ldhb )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA_src
    integer          :: ldda
    double precision :: hB_dst(*)
    integer          :: ldhb
end subroutine magmaf_dgetmatrix

subroutine magmaf_dcopymatrix( m, n, dA_src, ldda, dB_dst, lddb )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA_src
    integer          :: ldda
    magma_devptr_t   :: dB_dst
    integer          :: lddb
end subroutine magmaf_dcopymatrix

subroutine magmaf_dsetmatrix_async( m, n, hA_src, ldha, dB_dst, lddb, queue )
    integer          :: m
    integer          :: n
    double precision :: hA_src(*)
    integer          :: ldha
    magma_devptr_t   :: dB_dst
    integer          :: lddb
    integer          :: queue
end subroutine magmaf_dsetmatrix_async

subroutine magmaf_dgetmatrix_async( m, n, dA_src, ldda, hB_dst, ldhb, queue )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA_src
    integer          :: ldda
    double precision :: hB_dst(*)
    integer          :: ldhb
    integer          :: queue
end subroutine magmaf_dgetmatrix_async

subroutine magmaf_dcopymatrix_async( m, n, dA_src, ldda, dB_dst, lddb, queue )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA_src
    integer          :: ldda
    magma_devptr_t   :: dB_dst
    integer          :: lddb
    integer          :: queue
end subroutine magmaf_dcopymatrix_async

subroutine magmaf_idamax( n, dx, incx )
    integer          :: n
    magma_devptr_t   :: dx
    integer          :: incx
end subroutine magmaf_idamax

subroutine magmaf_idamin( n, dx, incx )
    integer          :: n
    magma_devptr_t   :: dx
    integer          :: incx
end subroutine magmaf_idamin

subroutine magmaf_daxpy( n, alpha, dx, incx, dy, incy )
    integer          :: n
    double precision :: alpha
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: dy
    integer          :: incy
end subroutine magmaf_daxpy

subroutine magmaf_dcopy( n, dx, incx, dy, incy )
    integer          :: n
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: dy
    integer          :: incy
end subroutine magmaf_dcopy

subroutine magmaf_drot( n, dx, incx, dy, incy, dc, ds )
    integer          :: n
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: dy
    integer          :: incy
    double precision :: dc
    double precision :: ds
end subroutine magmaf_drot

subroutine magmaf_drotm( n, dx, incx, dy, incy, param )
    integer          :: n
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: dy
    integer          :: incy
    magma_devptr_t   :: param
end subroutine magmaf_drotm

subroutine magmaf_drotmg( d1, d2, x1, y1, param )
    magma_devptr_t   :: d1
    magma_devptr_t   :: d2
    magma_devptr_t   :: x1
    magma_devptr_t   :: y1
    magma_devptr_t   :: param
end subroutine magmaf_drotmg

subroutine magmaf_dscal( n, alpha, dx, incx )
    integer          :: n
    double precision :: alpha
    magma_devptr_t   :: dx
    integer          :: incx
end subroutine magmaf_dscal

subroutine magmaf_dswap( n, dx, incx, dy, incy )
    integer          :: n
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: dy
    integer          :: incy
end subroutine magmaf_dswap

subroutine magmaf_dgemv( transA, m, n, alpha, dA, ldda, dx, incx, beta, dy, incy )
    character        :: transA
    integer          :: m
    integer          :: n
    double precision :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dx
    integer          :: incx
    double precision :: beta
    magma_devptr_t   :: dy
    integer          :: incy
end subroutine magmaf_dgemv

subroutine magmaf_dger( m, n, alpha, dx, incx, dy, incy, dA, ldda )
    integer          :: m
    integer          :: n
    double precision :: alpha
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: dy
    integer          :: incy
    magma_devptr_t   :: dA
    integer          :: ldda
end subroutine magmaf_dger

subroutine magmaf_dsymv( uplo, n, alpha, dA, ldda, dx, incx, beta, dy, incy )
    character        :: uplo
    integer          :: n
    double precision :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dx
    integer          :: incx
    double precision :: beta
    magma_devptr_t   :: dy
    integer          :: incy
end subroutine magmaf_dsymv

subroutine magmaf_dsyr( uplo, n, alpha, dx, incx, dA, ldda )
    character        :: uplo
    integer          :: n
    double precision :: alpha
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: dA
    integer          :: ldda
end subroutine magmaf_dsyr

subroutine magmaf_dsyr2( uplo, n, alpha, dx, incx, dy, incy, dA, ldda )
    character        :: uplo
    integer          :: n
    double precision :: alpha
    magma_devptr_t   :: dx
    integer          :: incx
    magma_devptr_t   :: dy
    integer          :: incy
    magma_devptr_t   :: dA
    integer          :: ldda
end subroutine magmaf_dsyr2

subroutine magmaf_dtrmv( uplo, trans, diag, n, dA, ldda, dx, incx )
    character        :: uplo
    character        :: trans
    character        :: diag
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dx
    integer          :: incx
end subroutine magmaf_dtrmv

subroutine magmaf_dtrsv( uplo, trans, diag, n, dA, ldda, dx, incx )
    character        :: uplo
    character        :: trans
    character        :: diag
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dx
    integer          :: incx
end subroutine magmaf_dtrsv

subroutine magmaf_dgemm( transA, transB, m, n, k, alpha, dA, ldda, dB, lddb, beta, dC,  &
        lddc )
    character        :: transA
    character        :: transB
    integer          :: m
    integer          :: n
    integer          :: k
    double precision :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    double precision :: beta
    magma_devptr_t   :: dC
    integer          :: lddc
end subroutine magmaf_dgemm

subroutine magmaf_dsymm( side, uplo, m, n, alpha, dA, ldda, dB, lddb, beta, dC, lddc )
    character        :: side
    character        :: uplo
    integer          :: m
    integer          :: n
    double precision :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    double precision :: beta
    magma_devptr_t   :: dC
    integer          :: lddc
end subroutine magmaf_dsymm

subroutine magmaf_dsyr2k( uplo, trans, n, k, alpha, dA, ldda, dB, lddb, beta, dC, lddc )
    character        :: uplo
    character        :: trans
    integer          :: n
    integer          :: k
    double precision :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    double precision :: beta
    magma_devptr_t   :: dC
    integer          :: lddc
end subroutine magmaf_dsyr2k

subroutine magmaf_dsyrk( uplo, trans, n, k, alpha, dA, ldda, beta, dC, lddc )
    character        :: uplo
    character        :: trans
    integer          :: n
    integer          :: k
    double precision :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    double precision :: beta
    magma_devptr_t   :: dC
    integer          :: lddc
end subroutine magmaf_dsyrk

subroutine magmaf_dtrmm( side, uplo, trans, diag, m, n, alpha, dA, ldda, dB, lddb )
    character        :: side
    character        :: uplo
    character        :: trans
    character        :: diag
    integer          :: m
    integer          :: n
    double precision :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
end subroutine magmaf_dtrmm

subroutine magmaf_dtrsm( side, uplo, trans, diag, m, n, alpha, dA, ldda, dB, lddb )
    character        :: side
    character        :: uplo
    character        :: trans
    character        :: diag
    integer          :: m
    integer          :: n
    double precision :: alpha
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
end subroutine magmaf_dtrsm

end interface

end module magmablas_dfortran
