!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!  This file is AUTOMATICALLY GENERATED by:
!!  ../tools/fortran_wrappers.pl ../include/magma_s.i
!!  Do not edit.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

module magma_sfortran

use magma_param

implicit none

!---- Fortran interfaces to MAGMA subroutines ----
interface

integer function magmaf_get_spotrf_nb( m )
    integer :: m
end function magmaf_get_spotrf_nb

integer function magmaf_get_sgetrf_nb( m )
    integer :: m
end function magmaf_get_sgetrf_nb

integer function magmaf_get_sgetri_nb( m )
    integer :: m
end function magmaf_get_sgetri_nb

integer function magmaf_get_sgeqp3_nb( m )
    integer :: m
end function magmaf_get_sgeqp3_nb

integer function magmaf_get_sgeqrf_nb( m )
    integer :: m
end function magmaf_get_sgeqrf_nb

integer function magmaf_get_sgeqlf_nb( m )
    integer :: m
end function magmaf_get_sgeqlf_nb

integer function magmaf_get_sgehrd_nb( m )
    integer :: m
end function magmaf_get_sgehrd_nb

integer function magmaf_get_ssytrd_nb( m )
    integer :: m
end function magmaf_get_ssytrd_nb

integer function magmaf_get_sgelqf_nb( m )
    integer :: m
end function magmaf_get_sgelqf_nb

integer function magmaf_get_sgebrd_nb( m )
    integer :: m
end function magmaf_get_sgebrd_nb

integer function magmaf_get_ssygst_nb( m )
    integer :: m
end function magmaf_get_ssygst_nb

integer function magmaf_get_sgesvd_nb( m )
    integer :: m
end function magmaf_get_sgesvd_nb

integer function magmaf_get_ssygst_nb_m( m )
    integer :: m
end function magmaf_get_ssygst_nb_m

subroutine magmaf_get_sbulge_nb( m, nbthreads )
    integer          :: m
    integer          :: nbthreads
end subroutine magmaf_get_sbulge_nb

subroutine magmaf_sbulge_get_Vblksiz( m, nb, nbthreads )
    integer          :: m
    integer          :: nb
    integer          :: nbthreads
end subroutine magmaf_sbulge_get_Vblksiz

subroutine magmaf_get_sbulge_gcperf(  )
end subroutine magmaf_get_sbulge_gcperf

subroutine magmaf_smove_eig( range, n, w, il, iu, vl, vu, m )
    character        :: range
    integer          :: n
    real             :: w(*)
    integer          :: il(*)
    integer          :: iu(*)
    real             :: vl
    real             :: vu
    integer          :: m
end subroutine magmaf_smove_eig

subroutine magmaf_sgebrd( m, n, A, lda, d, e, tauq, taup, work, lwork, info )
    integer          :: m
    integer          :: n
    real             :: A(*)
    integer          :: lda
    real             :: d(*)
    real             :: e(*)
    real             :: tauq(*)
    real             :: taup(*)
    real             :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magmaf_sgebrd

subroutine magmaf_sgehrd2( n, ilo, ihi, A, lda, tau, work, lwork, info )
    integer          :: n
    integer          :: ilo
    integer          :: ihi
    real             :: A(*)
    integer          :: lda
    real             :: tau(*)
    real             :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magmaf_sgehrd2

subroutine magmaf_sgehrd( n, ilo, ihi, A, lda, tau, work, lwork, dT, info )
    integer          :: n
    integer          :: ilo
    integer          :: ihi
    real             :: A(*)
    integer          :: lda
    real             :: tau(*)
    real             :: work(*)
    integer          :: lwork
    magma_devptr_t   :: dT
    integer          :: info
end subroutine magmaf_sgehrd

subroutine magmaf_sgelqf( m, n, A, lda, tau, work, lwork, info )
    integer          :: m
    integer          :: n
    real             :: A(*)
    integer          :: lda
    real             :: tau(*)
    real             :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magmaf_sgelqf

subroutine magmaf_sgeqlf( m, n, A, lda, tau, work, lwork, info )
    integer          :: m
    integer          :: n
    real             :: A(*)
    integer          :: lda
    real             :: tau(*)
    real             :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magmaf_sgeqlf

subroutine magmaf_sgeqrf( m, n, A, lda, tau, work, lwork, info )
    integer          :: m
    integer          :: n
    real             :: A(*)
    integer          :: lda
    real             :: tau(*)
    real             :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magmaf_sgeqrf

subroutine magmaf_sgeqrf4( num_gpus, m, n, a, lda, tau, work, lwork, info )
    integer          :: num_gpus
    integer          :: m
    integer          :: n
    real             :: a(*)
    integer          :: lda
    real             :: tau(*)
    real             :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magmaf_sgeqrf4

subroutine magmaf_sgeqrf_ooc( m, n, A, lda, tau, work, lwork, info )
    integer          :: m
    integer          :: n
    real             :: A(*)
    integer          :: lda
    real             :: tau(*)
    real             :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magmaf_sgeqrf_ooc

subroutine magmaf_sgesv( n, nrhs, A, lda, ipiv, B, ldb, info )
    integer          :: n
    integer          :: nrhs
    real             :: A(*)
    integer          :: lda
    integer          :: ipiv(*)
    real             :: B(*)
    integer          :: ldb
    integer          :: info
end subroutine magmaf_sgesv

subroutine magmaf_sgetrf( m, n, A, lda, ipiv, info )
    integer          :: m
    integer          :: n
    real             :: A(*)
    integer          :: lda
    integer          :: ipiv(*)
    integer          :: info
end subroutine magmaf_sgetrf

subroutine magmaf_sposv( uplo, n, nrhs, A, lda, B, ldb, info )
    character        :: uplo
    integer          :: n
    integer          :: nrhs
    real             :: A(*)
    integer          :: lda
    real             :: B(*)
    integer          :: ldb
    integer          :: info
end subroutine magmaf_sposv

subroutine magmaf_spotrf( uplo, n, A, lda, info )
    character        :: uplo
    integer          :: n
    real             :: A(*)
    integer          :: lda
    integer          :: info
end subroutine magmaf_spotrf

subroutine magmaf_spotri( uplo, n, A, lda, info )
    character        :: uplo
    integer          :: n
    real             :: A(*)
    integer          :: lda
    integer          :: info
end subroutine magmaf_spotri

subroutine magmaf_slauum( uplo, n, A, lda, info )
    character        :: uplo
    integer          :: n
    real             :: A(*)
    integer          :: lda
    integer          :: info
end subroutine magmaf_slauum

subroutine magmaf_strtri( uplo, diag, n, A, lda, info )
    character        :: uplo
    character        :: diag
    integer          :: n
    real             :: A(*)
    integer          :: lda
    integer          :: info
end subroutine magmaf_strtri

subroutine magmaf_ssytrd( uplo, n, A, lda, d, e, tau, work, lwork, info )
    character        :: uplo
    integer          :: n
    real             :: A(*)
    integer          :: lda
    real             :: d(*)
    real             :: e(*)
    real             :: tau(*)
    real             :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magmaf_ssytrd

subroutine magmaf_sorgqr( m, n, k, a, lda, tau, dT, nb, info )
    integer          :: m
    integer          :: n
    integer          :: k
    real             :: a(*)
    integer          :: lda
    real             :: tau(*)
    magma_devptr_t   :: dT
    integer          :: nb
    integer          :: info
end subroutine magmaf_sorgqr

subroutine magmaf_sorgqr2( m, n, k, a, lda, tau, info )
    integer          :: m
    integer          :: n
    integer          :: k
    real             :: a(*)
    integer          :: lda
    real             :: tau(*)
    integer          :: info
end subroutine magmaf_sorgqr2

subroutine magmaf_sormql( side, trans, m, n, k, a, lda, tau, c, ldc, work, lwork, info )
    character        :: side
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: k
    real             :: a(*)
    integer          :: lda
    real             :: tau(*)
    real             :: c(*)
    integer          :: ldc
    real             :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magmaf_sormql

subroutine magmaf_sormqr( side, trans, m, n, k, a, lda, tau, c, ldc, work, lwork, info )
    character        :: side
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: k
    real             :: a(*)
    integer          :: lda
    real             :: tau(*)
    real             :: c(*)
    integer          :: ldc
    real             :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magmaf_sormqr

subroutine magmaf_sormtr( side, uplo, trans, m, n, a, lda, tau, c, ldc, work, lwork, info  &
        )
    character        :: side
    character        :: uplo
    character        :: trans
    integer          :: m
    integer          :: n
    real             :: a(*)
    integer          :: lda
    real             :: tau(*)
    real             :: c(*)
    integer          :: ldc
    real             :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magmaf_sormtr

subroutine magmaf_sorghr( n, ilo, ihi, a, lda, tau, dT, nb, info )
    integer          :: n
    integer          :: ilo
    integer          :: ihi
    real             :: a(*)
    integer          :: lda
    real             :: tau(*)
    magma_devptr_t   :: dT
    integer          :: nb
    integer          :: info
end subroutine magmaf_sorghr

subroutine magmaf_sgeev( jobvl, jobvr, n, a, lda, wr, wi, vl, ldvl, vr, ldvr, work,  &
        lwork, info )
    character        :: jobvl
    character        :: jobvr
    integer          :: n
    real             :: a(*)
    integer          :: lda
    real             :: wr(*)
    real             :: wi(*)
    real             :: vl(*)
    integer          :: ldvl
    real             :: vr(*)
    integer          :: ldvr
    real             :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magmaf_sgeev

subroutine magmaf_sgeqp3( m, n, a, lda, jpvt, tau, work, lwork, info )
    integer          :: m
    integer          :: n
    real             :: a(*)
    integer          :: lda
    integer          :: jpvt(*)
    real             :: tau(*)
    real             :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magmaf_sgeqp3

subroutine magmaf_sgesvd( jobu, jobvt, m, n, a, lda, s, u, ldu, vt, ldvt, work, lwork,  &
        info )
    character        :: jobu
    character        :: jobvt
    integer          :: m
    integer          :: n
    real             :: a(*)
    integer          :: lda
    real             :: s(*)
    real             :: u(*)
    integer          :: ldu
    real             :: vt(*)
    integer          :: ldvt
    real             :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magmaf_sgesvd

subroutine magmaf_ssyevd( jobz, uplo, n, a, lda, w, work, lwork, iwork, liwork, info )
    character        :: jobz
    character        :: uplo
    integer          :: n
    real             :: a(*)
    integer          :: lda
    real             :: w(*)
    real             :: work(*)
    integer          :: lwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magmaf_ssyevd

subroutine magmaf_ssyevdx( jobz, range, uplo, n, a, lda, vl, vu, il, iu, m, w, work,  &
        lwork, iwork, liwork, info )
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    real             :: a(*)
    integer          :: lda
    real             :: vl
    real             :: vu
    integer          :: il
    integer          :: iu
    integer          :: m
    real             :: w(*)
    real             :: work(*)
    integer          :: lwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magmaf_ssyevdx

subroutine magmaf_ssyevdx_2stage( jobz, range, uplo, n, a, lda, vl, vu, il, iu, m, w,  &
        work, lwork, iwork, liwork, info )
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    real             :: a(*)
    integer          :: lda
    real             :: vl
    real             :: vu
    integer          :: il
    integer          :: iu
    integer          :: m
    real             :: w(*)
    real             :: work(*)
    integer          :: lwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magmaf_ssyevdx_2stage

subroutine magmaf_ssygvd( itype, jobz, uplo, n, a, lda, b, ldb, w, work, lwork, iwork,  &
        liwork, info )
    integer          :: itype
    character        :: jobz
    character        :: uplo
    integer          :: n
    real             :: a(*)
    integer          :: lda
    real             :: b(*)
    integer          :: ldb
    real             :: w(*)
    real             :: work(*)
    integer          :: lwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magmaf_ssygvd

subroutine magmaf_ssygvdx( itype, jobz, range, uplo, n, a, lda, b, ldb, vl, vu, il, iu,  &
        m, w, work, lwork, iwork, liwork, info )
    integer          :: itype
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    real             :: a(*)
    integer          :: lda
    real             :: b(*)
    integer          :: ldb
    real             :: vl
    real             :: vu
    integer          :: il
    integer          :: iu
    integer          :: m
    real             :: w(*)
    real             :: work(*)
    integer          :: lwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magmaf_ssygvdx

subroutine magmaf_ssygvdx_2stage( itype, jobz, range, uplo, n, a, lda, b, ldb, vl, vu,  &
        il, iu, m, w, work, lwork, iwork, liwork, info )
    integer          :: itype
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    real             :: a(*)
    integer          :: lda
    real             :: b(*)
    integer          :: ldb
    real             :: vl
    real             :: vu
    integer          :: il
    integer          :: iu
    integer          :: m
    real             :: w(*)
    real             :: work(*)
    integer          :: lwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magmaf_ssygvdx_2stage

subroutine magmaf_sstedx( range, n, vl, vu, il, iu, D, E, Z, ldz, rwork, lrwork, iwork,  &
        liwork, dwork, info )
    character        :: range
    integer          :: n
    real             :: vl
    real             :: vu
    integer          :: il
    integer          :: iu
    real             :: D(*)
    real             :: E(*)
    real             :: Z(*)
    integer          :: ldz
    real             :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    real             :: dwork(*)
    integer          :: info
end subroutine magmaf_sstedx

subroutine magmaf_ssygst( itype, uplo, n, a, lda, b, ldb, info )
    integer          :: itype
    character        :: uplo
    integer          :: n
    real             :: a(*)
    integer          :: lda
    real             :: b(*)
    integer          :: ldb
    integer          :: info
end subroutine magmaf_ssygst

subroutine magmaf_sgeev_m( jobvl, jobvr, n, A, lda, wr, wi, vl, ldvl, vr, ldvr, work,  &
        lwork, info )
    character        :: jobvl
    character        :: jobvr
    integer          :: n
    real             :: A(*)
    integer          :: lda
    real             :: wr(*)
    real             :: wi(*)
    real             :: vl(*)
    integer          :: ldvl
    real             :: vr(*)
    integer          :: ldvr
    real             :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magmaf_sgeev_m

subroutine magmaf_sgehrd_m( n, ilo, ihi, A, lda, tau, work, lwork, T, info )
    integer          :: n
    integer          :: ilo
    integer          :: ihi
    real             :: A(*)
    integer          :: lda
    real             :: tau(*)
    real             :: work(*)
    integer          :: lwork
    real             :: T(*)
    integer          :: info
end subroutine magmaf_sgehrd_m

subroutine magmaf_sorghr_m( n, ilo, ihi, A, lda, tau, T, nb, info )
    integer          :: n
    integer          :: ilo
    integer          :: ihi
    real             :: A(*)
    integer          :: lda
    real             :: tau(*)
    real             :: T(*)
    integer          :: nb
    integer          :: info
end subroutine magmaf_sorghr_m

subroutine magmaf_sorgqr_m( m, n, k, A, lda, tau, T, nb, info )
    integer          :: m
    integer          :: n
    integer          :: k
    real             :: A(*)
    integer          :: lda
    real             :: tau(*)
    real             :: T(*)
    integer          :: nb
    integer          :: info
end subroutine magmaf_sorgqr_m

subroutine magmaf_spotrf_m( num_gpus, uplo, n, A, lda, info )
    integer          :: num_gpus
    character        :: uplo
    integer          :: n
    real             :: A(*)
    integer          :: lda
    integer          :: info
end subroutine magmaf_spotrf_m

subroutine magmaf_sstedx_m( nrgpu, range, n, vl, vu, il, iu, D, E, Z, ldz, rwork,  &
        ldrwork, iwork, liwork, info )
    integer          :: nrgpu
    character        :: range
    integer          :: n
    real             :: vl
    real             :: vu
    integer          :: il
    integer          :: iu
    real             :: D(*)
    real             :: E(*)
    real             :: Z(*)
    integer          :: ldz
    real             :: rwork(*)
    integer          :: ldrwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magmaf_sstedx_m

subroutine magmaf_strsm_m( nrgpu, side, uplo, transa, diag, m, n, alpha, a, lda, b, ldb )
    integer          :: nrgpu
    character        :: side
    character        :: uplo
    character        :: transa
    character        :: diag
    integer          :: m
    integer          :: n
    real             :: alpha
    real             :: a(*)
    integer          :: lda
    real             :: b(*)
    integer          :: ldb
end subroutine magmaf_strsm_m

subroutine magmaf_sormqr_m( nrgpu, side, trans, m, n, k, a, lda, tau, c, ldc, work,  &
        lwork, info )
    integer          :: nrgpu
    character        :: side
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: k
    real             :: a(*)
    integer          :: lda
    real             :: tau(*)
    real             :: c(*)
    integer          :: ldc
    real             :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magmaf_sormqr_m

subroutine magmaf_sormtr_m( nrgpu, side, uplo, trans, m, n, a, lda, tau, c, ldc, work,  &
        lwork, info )
    integer          :: nrgpu
    character        :: side
    character        :: uplo
    character        :: trans
    integer          :: m
    integer          :: n
    real             :: a(*)
    integer          :: lda
    real             :: tau(*)
    real             :: c(*)
    integer          :: ldc
    real             :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magmaf_sormtr_m

subroutine magmaf_ssygst_m( nrgpu, itype, uplo, n, a, lda, b, ldb, info )
    integer          :: nrgpu
    integer          :: itype
    character        :: uplo
    integer          :: n
    real             :: a(*)
    integer          :: lda
    real             :: b(*)
    integer          :: ldb
    integer          :: info
end subroutine magmaf_ssygst_m

subroutine magmaf_ssyevd_m( nrgpu, jobz, uplo, n, a, lda, w, work, lwork, iwork, liwork,  &
        info )
    integer          :: nrgpu
    character        :: jobz
    character        :: uplo
    integer          :: n
    real             :: a(*)
    integer          :: lda
    real             :: w(*)
    real             :: work(*)
    integer          :: lwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magmaf_ssyevd_m

subroutine magmaf_ssygvd_m( nrgpu, itype, jobz, uplo, n, a, lda, b, ldb, w, work, lwork,  &
        iwork, liwork, info )
    integer          :: nrgpu
    integer          :: itype
    character        :: jobz
    character        :: uplo
    integer          :: n
    real             :: a(*)
    integer          :: lda
    real             :: b(*)
    integer          :: ldb
    real             :: w(*)
    real             :: work(*)
    integer          :: lwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magmaf_ssygvd_m

subroutine magmaf_ssyevdx_m( nrgpu, jobz, range, uplo, n, a, lda, vl, vu, il, iu, m, w,  &
        work, lwork, iwork, liwork, info )
    integer          :: nrgpu
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    real             :: a(*)
    integer          :: lda
    real             :: vl
    real             :: vu
    integer          :: il
    integer          :: iu
    integer          :: m
    real             :: w(*)
    real             :: work(*)
    integer          :: lwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magmaf_ssyevdx_m

subroutine magmaf_ssygvdx_m( nrgpu, itype, jobz, range, uplo, n, a, lda, b, ldb, vl, vu,  &
        il, iu, m, w, work, lwork, iwork, liwork, info )
    integer          :: nrgpu
    integer          :: itype
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    real             :: a(*)
    integer          :: lda
    real             :: b(*)
    integer          :: ldb
    real             :: vl
    real             :: vu
    integer          :: il
    integer          :: iu
    integer          :: m
    real             :: w(*)
    real             :: work(*)
    integer          :: lwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magmaf_ssygvdx_m

subroutine magmaf_ssyevdx_2stage_m( nrgpu, jobz, range, uplo, n, a, lda, vl, vu, il, iu,  &
        m, w, work, lwork, iwork, liwork, info )
    integer          :: nrgpu
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    real             :: a(*)
    integer          :: lda
    real             :: vl
    real             :: vu
    integer          :: il
    integer          :: iu
    integer          :: m
    real             :: w(*)
    real             :: work(*)
    integer          :: lwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magmaf_ssyevdx_2stage_m

subroutine magmaf_ssygvdx_2stage_m( nrgpu, itype, jobz, range, uplo, n, a, lda, b, ldb,  &
        vl, vu, il, iu, m, w, work, lwork, iwork, liwork, info )
    integer          :: nrgpu
    integer          :: itype
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    real             :: a(*)
    integer          :: lda
    real             :: b(*)
    integer          :: ldb
    real             :: vl
    real             :: vu
    integer          :: il
    integer          :: iu
    integer          :: m
    real             :: w(*)
    real             :: work(*)
    integer          :: lwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magmaf_ssygvdx_2stage_m

subroutine magmaf_sgels_gpu( trans, m, n, nrhs, dA, ldda, dB, lddb, hwork, lwork, info )
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: nrhs
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    real             :: hwork(*)
    integer          :: lwork
    integer          :: info
end subroutine magmaf_sgels_gpu

subroutine magmaf_sgels3_gpu( trans, m, n, nrhs, dA, ldda, dB, lddb, hwork, lwork, info )
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: nrhs
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    real             :: hwork(*)
    integer          :: lwork
    integer          :: info
end subroutine magmaf_sgels3_gpu

subroutine magmaf_sgelqf_gpu( m, n, dA, ldda, tau, work, lwork, info )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    real             :: tau(*)
    real             :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magmaf_sgelqf_gpu

subroutine magmaf_sgeqr2x_gpu( m, n, dA, ldda, dtau, dT, ddA, dwork, info )
    integer          :: m
    integer          :: n(*)
    magma_devptr_t   :: dA
    integer          :: ldda(*)
    magma_devptr_t   :: dtau
    magma_devptr_t   :: dT
    magma_devptr_t   :: ddA
    magma_devptr_t   :: dwork
    integer          :: info
end subroutine magmaf_sgeqr2x_gpu

subroutine magmaf_sgeqr2x2_gpu( m, n, dA, ldda, dtau, dT, ddA, dwork, info )
    integer          :: m
    integer          :: n(*)
    magma_devptr_t   :: dA
    integer          :: ldda(*)
    magma_devptr_t   :: dtau
    magma_devptr_t   :: dT
    magma_devptr_t   :: ddA
    magma_devptr_t   :: dwork
    integer          :: info
end subroutine magmaf_sgeqr2x2_gpu

subroutine magmaf_sgeqr2x3_gpu( m, n, dA, ldda, dtau, dT, ddA, dwork, info )
    integer          :: m
    integer          :: n(*)
    magma_devptr_t   :: dA
    integer          :: ldda(*)
    magma_devptr_t   :: dtau
    magma_devptr_t   :: dT
    magma_devptr_t   :: ddA
    magma_devptr_t   :: dwork
    integer          :: info
end subroutine magmaf_sgeqr2x3_gpu

subroutine magmaf_sgeqr2x4_gpu( m, n, dA, ldda, dtau, dT, ddA, dwork, info, stream )
    integer          :: m
    integer          :: n(*)
    magma_devptr_t   :: dA
    integer          :: ldda(*)
    magma_devptr_t   :: dtau
    magma_devptr_t   :: dT
    magma_devptr_t   :: ddA
    magma_devptr_t   :: dwork
    integer          :: info
    integer          :: stream
end subroutine magmaf_sgeqr2x4_gpu

subroutine magmaf_sgeqrf_gpu( m, n, dA, ldda, tau, dT, info )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    real             :: tau(*)
    magma_devptr_t   :: dT
    integer          :: info
end subroutine magmaf_sgeqrf_gpu

subroutine magmaf_sgeqrf2_gpu( m, n, dA, ldda, tau, info )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    real             :: tau(*)
    integer          :: info
end subroutine magmaf_sgeqrf2_gpu

subroutine magmaf_sgeqrf3_gpu( m, n, dA, ldda, tau, dT, info )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    real             :: tau(*)
    magma_devptr_t   :: dT
    integer          :: info
end subroutine magmaf_sgeqrf3_gpu

subroutine magmaf_sgeqrs_gpu( m, n, nrhs, dA, ldda, tau, dT, dB, lddb, hwork, lhwork,  &
        info )
    integer          :: m
    integer          :: n
    integer          :: nrhs
    magma_devptr_t   :: dA
    integer          :: ldda
    real             :: tau(*)
    magma_devptr_t   :: dT
    magma_devptr_t   :: dB
    integer          :: lddb
    real             :: hwork(*)
    integer          :: lhwork
    integer          :: info
end subroutine magmaf_sgeqrs_gpu

subroutine magmaf_sgeqrs3_gpu( m, n, nrhs, dA, ldda, tau, dT, dB, lddb, hwork, lhwork,  &
        info )
    integer          :: m
    integer          :: n
    integer          :: nrhs
    magma_devptr_t   :: dA
    integer          :: ldda
    real             :: tau(*)
    magma_devptr_t   :: dT
    magma_devptr_t   :: dB
    integer          :: lddb
    real             :: hwork(*)
    integer          :: lhwork
    integer          :: info
end subroutine magmaf_sgeqrs3_gpu

subroutine magmaf_sgessm_gpu( storev, m, n, k, ib, ipiv, dL1, lddl1, dL, lddl, dA, ldda,  &
        info )
    character        :: storev
    integer          :: m
    integer          :: n
    integer          :: k
    integer          :: ib
    integer          :: ipiv(*)
    magma_devptr_t   :: dL1
    integer          :: lddl1
    magma_devptr_t   :: dL
    integer          :: lddl
    magma_devptr_t   :: dA
    integer          :: ldda
    integer          :: info
end subroutine magmaf_sgessm_gpu

subroutine magmaf_sgesv_gpu( n, nrhs, dA, ldda, ipiv, dB, lddb, info )
    integer          :: n
    integer          :: nrhs
    magma_devptr_t   :: dA
    integer          :: ldda
    integer          :: ipiv(*)
    magma_devptr_t   :: dB
    integer          :: lddb
    integer          :: info
end subroutine magmaf_sgesv_gpu

subroutine magmaf_sgetf2_gpu( m, n, dA, lda, ipiv, info )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: lda
    integer          :: ipiv(*)
    integer          :: info
end subroutine magmaf_sgetf2_gpu

subroutine magmaf_sgetrf_gpu( m, n, dA, ldda, ipiv, info )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    integer          :: ipiv(*)
    integer          :: info
end subroutine magmaf_sgetrf_gpu

subroutine magmaf_sgetrf_m( num_gpus0, m, n, a, lda, ipiv, info )
    integer          :: num_gpus0
    integer          :: m
    integer          :: n
    real             :: a(*)
    integer          :: lda
    integer          :: ipiv(*)
    integer          :: info
end subroutine magmaf_sgetrf_m

subroutine magmaf_sgetrf_piv( m, n, NB, a, lda, ipiv, info )
    integer          :: m
    integer          :: n
    integer          :: NB
    real             :: a(*)
    integer          :: lda
    integer          :: ipiv(*)
    integer          :: info
end subroutine magmaf_sgetrf_piv

subroutine magmaf_sgetrf_nopiv_gpu( m, n, dA, ldda, info )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    integer          :: info
end subroutine magmaf_sgetrf_nopiv_gpu

subroutine magmaf_sgetri_gpu( n, dA, ldda, ipiv, dwork, lwork, info )
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    integer          :: ipiv(*)
    magma_devptr_t   :: dwork
    integer          :: lwork
    integer          :: info
end subroutine magmaf_sgetri_gpu

subroutine magmaf_sgetrs_gpu( trans, n, nrhs, dA, ldda, ipiv, dB, lddb, info )
    character        :: trans
    integer          :: n
    integer          :: nrhs
    magma_devptr_t   :: dA
    integer          :: ldda
    integer          :: ipiv(*)
    magma_devptr_t   :: dB
    integer          :: lddb
    integer          :: info
end subroutine magmaf_sgetrs_gpu

subroutine magmaf_slaqps2_gpu( m, n, offset, nb, kb, A, lda, jpvt, tau, vn1, vn2, auxv,  &
        dF, lddf )
    integer          :: m
    integer          :: n
    integer          :: offset
    integer          :: nb
    integer          :: kb(*)
    real             :: A(*)
    integer          :: lda
    integer          :: jpvt(*)
    real             :: tau(*)
    real             :: vn1(*)
    real             :: vn2(*)
    real             :: auxv(*)
    magma_devptr_t   :: dF
    integer          :: lddf
end subroutine magmaf_slaqps2_gpu

subroutine magmaf_slaqps3_gpu( m, n, offset, nb, kb, A, lda, jpvt, tau, vn1, vn2, auxv,  &
        dF, lddf )
    integer          :: m
    integer          :: n
    integer          :: offset
    integer          :: nb
    integer          :: kb(*)
    real             :: A(*)
    integer          :: lda
    integer          :: jpvt(*)
    real             :: tau(*)
    real             :: vn1(*)
    real             :: vn2(*)
    real             :: auxv(*)
    magma_devptr_t   :: dF
    integer          :: lddf
end subroutine magmaf_slaqps3_gpu

subroutine magmaf_slarf_gpu( m, n, v, tau, c, ldc, xnorm )
    integer          :: m
    integer          :: n
    real             :: v(*)
    real             :: tau(*)
    real             :: c(*)
    integer          :: ldc
    real             :: xnorm(*)
end subroutine magmaf_slarf_gpu

subroutine magmaf_slarfb_gpu( side, trans, direct, storev, m, n, k, dv, ldv, dt, ldt, dc,  &
        ldc, dwork, ldwork )
    character        :: side
    character        :: trans
    character        :: direct
    character        :: storev
    integer          :: m
    integer          :: n
    integer          :: k
    magma_devptr_t   :: dv
    integer          :: ldv
    magma_devptr_t   :: dt
    integer          :: ldt
    magma_devptr_t   :: dc
    integer          :: ldc
    magma_devptr_t   :: dwork
    integer          :: ldwork
end subroutine magmaf_slarfb_gpu

subroutine magmaf_slarfb2_gpu( m, n, k, dV, ldv, dT, ldt, dC, ldc, dwork, ldwork )
    integer          :: m
    integer          :: n
    integer          :: k
    magma_devptr_t   :: dV
    integer          :: ldv
    magma_devptr_t   :: dT
    integer          :: ldt
    magma_devptr_t   :: dC
    integer          :: ldc
    magma_devptr_t   :: dwork
    integer          :: ldwork
end subroutine magmaf_slarfb2_gpu

subroutine magmaf_slarfb_gpu_gemm( side, trans, direct, storev, m, n, k, dv, ldv, dt,  &
        ldt, dc, ldc, dwork, ldwork, dworkvt, ldworkvt )
    character        :: side
    character        :: trans
    character        :: direct
    character        :: storev
    integer          :: m
    integer          :: n
    integer          :: k
    real             :: dv(*)
    integer          :: ldv
    real             :: dt(*)
    integer          :: ldt
    real             :: dc(*)
    integer          :: ldc
    real             :: dwork(*)
    integer          :: ldwork
    real             :: dworkvt(*)
    integer          :: ldworkvt
end subroutine magmaf_slarfb_gpu_gemm

subroutine magmaf_sposv_gpu( uplo, n, nrhs, dA, ldda, dB, lddb, info )
    character        :: uplo
    integer          :: n
    integer          :: nrhs
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    integer          :: info
end subroutine magmaf_sposv_gpu

subroutine magmaf_spotf2_gpu( uplo, n, dA, lda, info )
    character        :: uplo
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: lda
    integer          :: info
end subroutine magmaf_spotf2_gpu

subroutine magmaf_spotrf_gpu( uplo, n, dA, ldda, info )
    character        :: uplo
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    integer          :: info
end subroutine magmaf_spotrf_gpu

subroutine magmaf_spotri_gpu( uplo, n, dA, ldda, info )
    character        :: uplo
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    integer          :: info
end subroutine magmaf_spotri_gpu

subroutine magmaf_slauum_gpu( uplo, n, dA, ldda, info )
    character        :: uplo
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    integer          :: info
end subroutine magmaf_slauum_gpu

subroutine magmaf_strtri_gpu( uplo, diag, n, dA, ldda, info )
    character        :: uplo
    character        :: diag
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
    integer          :: info
end subroutine magmaf_strtri_gpu

subroutine magmaf_ssytrd_gpu( uplo, n, da, ldda, d, e, tau, wa, ldwa, work, lwork, info )
    character        :: uplo
    integer          :: n
    magma_devptr_t   :: da
    integer          :: ldda
    real             :: d(*)
    real             :: e(*)
    real             :: tau(*)
    real             :: wa(*)
    integer          :: ldwa
    real             :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magmaf_ssytrd_gpu

subroutine magmaf_ssytrd2_gpu( uplo, n, da, ldda, d, e, tau, wa, ldwa, work, lwork,  &
        dwork, ldwork, info )
    character        :: uplo
    integer          :: n
    magma_devptr_t   :: da
    integer          :: ldda
    real             :: d(*)
    real             :: e(*)
    real             :: tau(*)
    real             :: wa(*)
    integer          :: ldwa
    real             :: work(*)
    integer          :: lwork
    magma_devptr_t   :: dwork
    integer          :: ldwork
    integer          :: info
end subroutine magmaf_ssytrd2_gpu

subroutine magmaf_ssytrd_sb2st( threads, uplo, n, nb, Vblksiz, A, lda, D, E, V, ldv, TAU,  &
        compT, T, ldt )
    integer          :: threads
    character        :: uplo
    integer          :: n
    integer          :: nb
    integer          :: Vblksiz
    real             :: A(*)
    integer          :: lda
    real             :: D(*)
    real             :: E(*)
    real             :: V(*)
    integer          :: ldv
    real             :: TAU(*)
    integer          :: compT
    real             :: T(*)
    integer          :: ldt
end subroutine magmaf_ssytrd_sb2st

subroutine magmaf_ssytrd_sy2sb( uplo, n, NB, a, lda, tau, work, lwork, dT, threads, info  &
        )
    character        :: uplo
    integer          :: n
    integer          :: NB
    real             :: a(*)
    integer          :: lda
    real             :: tau(*)
    real             :: work(*)
    integer          :: lwork
    magma_devptr_t   :: dT
    integer          :: threads
    integer          :: info
end subroutine magmaf_ssytrd_sy2sb

subroutine magmaf_spotrs_gpu( uplo, n, nrhs, dA, ldda, dB, lddb, info )
    character        :: uplo
    integer          :: n
    integer          :: nrhs
    magma_devptr_t   :: dA
    integer          :: ldda
    magma_devptr_t   :: dB
    integer          :: lddb
    integer          :: info
end subroutine magmaf_spotrs_gpu

subroutine magmaf_sssssm_gpu( storev, m1, n1, m2, n2, k, ib, dA1, ldda1, dA2, ldda2, dL1,  &
        lddl1, dL2, lddl2, IPIV, info )
    character        :: storev
    integer          :: m1
    integer          :: n1
    integer          :: m2
    integer          :: n2
    integer          :: k
    integer          :: ib
    magma_devptr_t   :: dA1
    integer          :: ldda1
    magma_devptr_t   :: dA2
    integer          :: ldda2
    magma_devptr_t   :: dL1
    integer          :: lddl1
    magma_devptr_t   :: dL2
    integer          :: lddl2
    integer          :: IPIV(*)
    integer          :: info
end subroutine magmaf_sssssm_gpu

subroutine magmaf_sorgqr_gpu( m, n, k, da, ldda, tau, dwork, nb, info )
    integer          :: m
    integer          :: n
    integer          :: k
    magma_devptr_t   :: da
    integer          :: ldda
    real             :: tau(*)
    magma_devptr_t   :: dwork
    integer          :: nb
    integer          :: info
end subroutine magmaf_sorgqr_gpu

subroutine magmaf_sormql2_gpu( side, trans, m, n, k, da, ldda, tau, dc, lddc, wa, ldwa,  &
        info )
    character        :: side
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: k
    magma_devptr_t   :: da
    integer          :: ldda
    real             :: tau(*)
    magma_devptr_t   :: dc
    integer          :: lddc
    real             :: wa(*)
    integer          :: ldwa
    integer          :: info
end subroutine magmaf_sormql2_gpu

subroutine magmaf_sormqr_gpu( side, trans, m, n, k, dA, ldda, tau, dC, lddc, hwork,  &
        lwork, dT, nb, info )
    character        :: side
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: k
    magma_devptr_t   :: dA
    integer          :: ldda
    real             :: tau(*)
    magma_devptr_t   :: dC
    integer          :: lddc
    real             :: hwork(*)
    integer          :: lwork
    magma_devptr_t   :: dT
    integer          :: nb
    integer          :: info
end subroutine magmaf_sormqr_gpu

subroutine magmaf_sormqr2_gpu( side, trans, m, n, k, da, ldda, tau, dc, lddc, wa, ldwa,  &
        info )
    character        :: side
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: k
    magma_devptr_t   :: da
    integer          :: ldda
    real             :: tau(*)
    magma_devptr_t   :: dc
    integer          :: lddc
    real             :: wa(*)
    integer          :: ldwa
    integer          :: info
end subroutine magmaf_sormqr2_gpu

subroutine magmaf_sormtr_gpu( side, uplo, trans, m, n, da, ldda, tau, dc, lddc, wa, ldwa,  &
        info )
    character        :: side
    character        :: uplo
    character        :: trans
    integer          :: m
    integer          :: n
    magma_devptr_t   :: da
    integer          :: ldda
    real             :: tau(*)
    magma_devptr_t   :: dc
    integer          :: lddc
    real             :: wa(*)
    integer          :: ldwa
    integer          :: info
end subroutine magmaf_sormtr_gpu

subroutine magmaf_sgeqp3_gpu( m, n, A, lda, jpvt, tau, work, lwork, info )
    integer          :: m
    integer          :: n
    real             :: A(*)
    integer          :: lda
    integer          :: jpvt(*)
    real             :: tau(*)
    real             :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magmaf_sgeqp3_gpu

subroutine magmaf_ssyevd_gpu( jobz, uplo, n, da, ldda, w, wa, ldwa, work, lwork, iwork,  &
        liwork, info )
    character        :: jobz
    character        :: uplo
    integer          :: n
    magma_devptr_t   :: da
    integer          :: ldda
    real             :: w(*)
    real             :: wa(*)
    integer          :: ldwa
    real             :: work(*)
    integer          :: lwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magmaf_ssyevd_gpu

subroutine magmaf_ssyevdx_gpu( jobz, range, uplo, n, da, ldda, vl, vu, il, iu, m, w, wa,  &
        ldwa, work, lwork, iwork, liwork, info )
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    magma_devptr_t   :: da
    integer          :: ldda
    real             :: vl
    real             :: vu
    integer          :: il
    integer          :: iu
    integer          :: m
    real             :: w(*)
    real             :: wa(*)
    integer          :: ldwa
    real             :: work(*)
    integer          :: lwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magmaf_ssyevdx_gpu

subroutine magmaf_ssygst_gpu( itype, uplo, n, da, ldda, db, lddb, info )
    integer          :: itype
    character        :: uplo
    integer          :: n
    magma_devptr_t   :: da
    integer          :: ldda
    magma_devptr_t   :: db
    integer          :: lddb
    integer          :: info
end subroutine magmaf_ssygst_gpu

subroutine magmaf_sprint( m, n, A, lda )
    integer          :: m
    integer          :: n
    real             :: A(*)
    integer          :: lda
end subroutine magmaf_sprint

subroutine magmaf_sprint_gpu( m, n, dA, ldda )
    integer          :: m
    integer          :: n
    magma_devptr_t   :: dA
    integer          :: ldda
end subroutine magmaf_sprint_gpu

end interface

!---- Fortran-only subroutines (see ../tools/fortran_wrappers.pl to edit) ----
contains

subroutine magmaf_soff1d( ptrNew, ptrOld, inc, i)
    magma_devptr_t   :: ptrNew
    magma_devptr_t   :: ptrOld
    integer          :: inc, i

    ptrNew = ptrOld + (i-1) * inc * sizeof_real
end subroutine magmaf_soff1d

subroutine magmaf_soff2d( ptrNew, ptrOld, lda, i, j)
    magma_devptr_t   :: ptrNew
    magma_devptr_t   :: ptrOld
    integer          :: lda, i, j

    ptrNew = ptrOld + ((j-1) * lda + (i-1)) * sizeof_real
end subroutine magmaf_soff2d

end module magma_sfortran
