CHDR = \
magma_c.h magmablas_c.h magma_clapack.h magma_cbulge.h magma_cbulgeinc.h magma_cgehrd_m.h

DHDR = \
magma_d.h magma_ds.h magmablas_d.h magmablas_ds.h magma_dlapack.h magma_dbulge.h magma_dbulgeinc.h magma_dgehrd_m.h

SHDR = \
magma_s.h magmablas_s.h magma_slapack.h magma_sbulge.h magma_sbulgeinc.h magma_sgehrd_m.h

CSRC = \


DSRC = \


SSRC = \

