# See Makefile.src for list of files in this directory.
# This makefile simply forwards commands to the top-level makefile.

top  := ../..
cdir := testing/lin

default: $(cdir)

include $(top)/Makefile.subdir
