#######################################################################
#  This makefile creates the test programs for the linear equation
#  routines in LAPACK.  The test files are grouped as follows:
#
#       ALINTST -- Auxiliary test routines
#       SLINTST -- Single precision real test routines
#       CLINTST -- Single precision complex test routines
#       SCLNTST -- Single and Complex routines in common
#       DLINTST -- Double precision real test routines
#       ZLINTST -- Double precision complex test routines
#       DZLNTST -- Double and Double Complex routines in common
#
#  Test programs can be generated for all or some of the four different
#  precisions.  Enter make followed by one or more of the data types
#  desired.  Some examples:
#       make single
#       make single complex
#       make single double complex complex16
#  Alternatively, the command
#       make
#  without any arguments creates all four test programs.
#  The executable files are called
#       xlintims, xlintimd, xlintimc, and xlintimz
#  and are created in the next higher directory level.
#
#  To remove the object files after the executable files have been
#  created, enter
#       make clean
#  On some systems, you can force the source files to be recompiled by
#  entering (for example)
#       make single FRC=FRC
#
#######################################################################

# push previous directory
dir_stack := $(dir_stack) $(cdir)
cdir      := testing/lin
# ----------------------------------------------------------------------


# sources for liblapacktest.a, if Fortran is NOT available -- dummy stub functions.
liblapacktest_src := \
	$(cdir)/magma_z_no_fortran.cpp

# sources for liblapacktest.a, if Fortran IS available.
liblapacktest_src += \
	$(cdir)/zbdt01.f  \
	$(cdir)/zget22.f  \
	$(cdir)/zhet21.f  \
	$(cdir)/zhst01.f  \
	$(cdir)/zunt01.f  \
	$(cdir)/zqpt01.f  \
	$(cdir)/zqrt02.f  \
	$(cdir)/zlarfy.f  \
	$(cdir)/zstt21.f  \
	\
	$(cdir)/cbdt01.f  \
	$(cdir)/cget22.f  \
	$(cdir)/chet21.f  \
	$(cdir)/chst01.f  \
	$(cdir)/cunt01.f  \
	$(cdir)/cqpt01.f  \
	$(cdir)/cqrt02.f  \
	$(cdir)/clarfy.f  \
	$(cdir)/cstt21.f  \
	\
	$(cdir)/dbdt01.f  \
	$(cdir)/dget22.f  \
	$(cdir)/dsyt21.f  \
	$(cdir)/dhst01.f  \
	$(cdir)/dort01.f  \
	$(cdir)/dqpt01.f  \
	$(cdir)/dqrt02.f  \
	$(cdir)/dlarfy.f  \
	$(cdir)/dstt21.f  \
	\
	$(cdir)/sbdt01.f  \
	$(cdir)/sget22.f  \
	$(cdir)/ssyt21.f  \
	$(cdir)/shst01.f  \
	$(cdir)/sort01.f  \
	$(cdir)/sqpt01.f  \
	$(cdir)/sqrt02.f  \
	$(cdir)/slarfy.f  \
	$(cdir)/sstt21.f



#######################################################################

ALINTST = \
   aladhd.$(o_ext) alaerh.$(o_ext) alaesm.$(o_ext) alahd.$(o_ext) alareq.$(o_ext) \
   alasum.$(o_ext) alasvm.$(o_ext) chkxer.$(o_ext) icopy.$(o_ext) ilaenv.$(o_ext) xlaenv.$(o_ext) xerbla.$(o_ext)

SCLNTST = slaord.$(o_ext)

DZLNTST = dlaord.$(o_ext)

SLINTST = schkaa.$(o_ext) \
   schkeq.$(o_ext) schkgb.$(o_ext) schkge.$(o_ext) schkgt.$(o_ext) \
   schklq.$(o_ext) schkpb.$(o_ext) schkpo.$(o_ext) schkps.$(o_ext) schkpp.$(o_ext) \
   schkpt.$(o_ext) schkq3.$(o_ext) schkql.$(o_ext) schkqp.$(o_ext) schkqr.$(o_ext) schkrq.$(o_ext) \
   schktb.$(o_ext) schktp.$(o_ext) schktr.$(o_ext) \
   schktz.$(o_ext) \
   sdrvgt.$(o_ext) sdrvls.$(o_ext) sdrvpb.$(o_ext) \
   sdrvpp.$(o_ext) sdrvpt.$(o_ext) sdrvsp.$(o_ext) \
   serrgt.$(o_ext) serrlq.$(o_ext) serrls.$(o_ext) \
   serrps.$(o_ext) serrql.$(o_ext) serrqp.$(o_ext) serrqr.$(o_ext) \
   serrrq.$(o_ext) serrtr.$(o_ext) serrtz.$(o_ext) \
   sgbt01.$(o_ext) sgbt02.$(o_ext) sgbt05.$(o_ext) sgelqs.$(o_ext) sgeqls.$(o_ext) sgeqrs.$(o_ext) \
   sgerqs.$(o_ext) sget01.$(o_ext) sget02.$(o_ext) \
   sget03.$(o_ext) sget04.$(o_ext) sget06.$(o_ext) sget07.$(o_ext) sgtt01.$(o_ext) sgtt02.$(o_ext) \
   sgtt05.$(o_ext) slaptm.$(o_ext) slarhs.$(o_ext) slatb4.$(o_ext) slatb5.$(o_ext) slattb.$(o_ext) slattp.$(o_ext) \
   slattr.$(o_ext) slavsp.$(o_ext) slavsy.$(o_ext) slqt01.$(o_ext) slqt02.$(o_ext) \
   slqt03.$(o_ext) spbt01.$(o_ext) spbt02.$(o_ext) spbt05.$(o_ext) spot01.$(o_ext) \
   spot02.$(o_ext) spot03.$(o_ext) spot05.$(o_ext) spst01.$(o_ext) sppt01.$(o_ext) \
   sppt02.$(o_ext) sppt03.$(o_ext) sppt05.$(o_ext) sptt01.$(o_ext) sptt02.$(o_ext) \
   sptt05.$(o_ext) sqlt01.$(o_ext) sqlt02.$(o_ext) sqlt03.$(o_ext) sqpt01.$(o_ext) \
   sqrt01.$(o_ext) sqrt02.$(o_ext) sqrt03.$(o_ext) sqrt11.$(o_ext) sqrt12.$(o_ext) \
   sqrt13.$(o_ext) sqrt14.$(o_ext) sqrt15.$(o_ext) sqrt16.$(o_ext) sqrt17.$(o_ext) \
   srqt01.$(o_ext) srqt02.$(o_ext) srqt03.$(o_ext) srzt01.$(o_ext) srzt02.$(o_ext) \
   sspt01.$(o_ext) ssyt01.$(o_ext) \
   stbt02.$(o_ext) stbt03.$(o_ext) stbt05.$(o_ext) stbt06.$(o_ext) stpt01.$(o_ext) \
   stpt02.$(o_ext) stpt03.$(o_ext) stpt05.$(o_ext) stpt06.$(o_ext) strt01.$(o_ext) \
   strt02.$(o_ext) strt03.$(o_ext) strt05.$(o_ext) strt06.$(o_ext) \
   stzt01.$(o_ext) stzt02.$(o_ext) sgennd.$(o_ext)

SLINTST += serrvx.$(o_ext) sdrvge.$(o_ext) serrge.$(o_ext) sdrvgb.$(o_ext) sdrvpo.$(o_ext) \
	serrpo.$(o_ext)

CLINTST = cchkaa.$(o_ext) \
   cchkeq.$(o_ext) cchkgb.$(o_ext) cchkge.$(o_ext) cchkgt.$(o_ext) \
   cchklq.$(o_ext) cchkpb.$(o_ext) \
   cchkpo.$(o_ext) cchkps.$(o_ext) cchkpp.$(o_ext) cchkpt.$(o_ext) cchkq3.$(o_ext) cchkql.$(o_ext) cchkqp.$(o_ext) \
   cchkqr.$(o_ext) cchkrq.$(o_ext) cchktb.$(o_ext) \
   cchktp.$(o_ext) cchktr.$(o_ext) cchktz.$(o_ext) \
   cdrvgt.$(o_ext) cdrvhp.$(o_ext) \
   cdrvls.$(o_ext) cdrvpb.$(o_ext) cdrvpp.$(o_ext) cdrvpt.$(o_ext) \
   cdrvsp.$(o_ext) \
   cerrgt.$(o_ext) cerrlq.$(o_ext) \
   cerrls.$(o_ext) cerrps.$(o_ext) cerrql.$(o_ext) cerrqp.$(o_ext) \
   cerrqr.$(o_ext) cerrrq.$(o_ext) cerrtr.$(o_ext) cerrtz.$(o_ext) \
   cgbt01.$(o_ext) cgbt02.$(o_ext) cgbt05.$(o_ext) cgelqs.$(o_ext) cgeqls.$(o_ext) cgeqrs.$(o_ext) \
   cgerqs.$(o_ext) cget01.$(o_ext) cget02.$(o_ext) \
   cget03.$(o_ext) cget04.$(o_ext) cget07.$(o_ext) cgtt01.$(o_ext) cgtt02.$(o_ext) \
   cgtt05.$(o_ext) chet01.$(o_ext) chpt01.$(o_ext) claipd.$(o_ext) claptm.$(o_ext) clarhs.$(o_ext) clatb4.$(o_ext) clatb5.$(o_ext) \
   clatsp.$(o_ext) clatsy.$(o_ext) clattb.$(o_ext) clattp.$(o_ext) clattr.$(o_ext) \
   clavhe.$(o_ext) clavhp.$(o_ext) clavsp.$(o_ext) clavsy.$(o_ext) clqt01.$(o_ext) \
   clqt02.$(o_ext) clqt03.$(o_ext) cpbt01.$(o_ext) cpbt02.$(o_ext) cpbt05.$(o_ext) \
   cpot01.$(o_ext) cpot02.$(o_ext) cpot03.$(o_ext) cpot05.$(o_ext) cpst01.$(o_ext) \
   cppt01.$(o_ext) cppt02.$(o_ext) cppt03.$(o_ext) cppt05.$(o_ext) cptt01.$(o_ext) \
   cptt02.$(o_ext) cptt05.$(o_ext) cqlt01.$(o_ext) cqlt02.$(o_ext) cqlt03.$(o_ext) \
   cqpt01.$(o_ext) cqrt01.$(o_ext) cqrt02.$(o_ext) cqrt03.$(o_ext) cqrt11.$(o_ext) \
   cqrt12.$(o_ext) cqrt13.$(o_ext) cqrt14.$(o_ext) cqrt15.$(o_ext) cqrt16.$(o_ext) \
   cqrt17.$(o_ext) crqt01.$(o_ext) crqt02.$(o_ext) crqt03.$(o_ext) crzt01.$(o_ext) crzt02.$(o_ext) \
   csbmv.$(o_ext)  cspt01.$(o_ext) \
   cspt02.$(o_ext) cspt03.$(o_ext) csyt01.$(o_ext) csyt02.$(o_ext) csyt03.$(o_ext) \
   ctbt02.$(o_ext) ctbt03.$(o_ext) ctbt05.$(o_ext) ctbt06.$(o_ext) ctpt01.$(o_ext) \
   ctpt02.$(o_ext) ctpt03.$(o_ext) ctpt05.$(o_ext) ctpt06.$(o_ext) ctrt01.$(o_ext) \
   ctrt02.$(o_ext) ctrt03.$(o_ext) ctrt05.$(o_ext) ctrt06.$(o_ext) \
   ctzt01.$(o_ext) ctzt02.$(o_ext) sget06.$(o_ext) cgennd.$(o_ext)

CLINTST += cerrvx.$(o_ext) cdrvge.$(o_ext) cdrvgb.$(o_ext) cerrge.$(o_ext) cdrvpo.$(o_ext) \
	cerrpo.$(o_ext)

DLINTST = dchkaa.$(o_ext) \
   dchkeq.$(o_ext) dchkgb.$(o_ext) dchkge.$(o_ext) dchkgt.$(o_ext) \
   dchklq.$(o_ext) dchkpb.$(o_ext) dchkpo.$(o_ext) dchkps.$(o_ext) dchkpp.$(o_ext) \
   dchkpt.$(o_ext) dchkq3.$(o_ext) dchkql.$(o_ext) dchkqp.$(o_ext) dchkqr.$(o_ext) dchkrq.$(o_ext) \
   dchktb.$(o_ext) dchktp.$(o_ext) dchktr.$(o_ext) \
   dchktz.$(o_ext) \
   ddrvgt.$(o_ext) ddrvls.$(o_ext) ddrvpb.$(o_ext) \
   ddrvpp.$(o_ext) ddrvpt.$(o_ext) ddrvsp.$(o_ext) \
   derrgt.$(o_ext) derrlq.$(o_ext) derrls.$(o_ext) \
   derrps.$(o_ext) derrql.$(o_ext) derrqp.$(o_ext) derrqr.$(o_ext) \
   derrrq.$(o_ext) derrtr.$(o_ext) derrtz.$(o_ext) \
   dgbt01.$(o_ext) dgbt02.$(o_ext) dgbt05.$(o_ext) dgelqs.$(o_ext) dgeqls.$(o_ext) dgeqrs.$(o_ext) \
   dgerqs.$(o_ext) dget01.$(o_ext) dget02.$(o_ext) \
   dget03.$(o_ext) dget04.$(o_ext) dget06.$(o_ext) dget07.$(o_ext) dgtt01.$(o_ext) dgtt02.$(o_ext) \
   dgtt05.$(o_ext) dlaptm.$(o_ext) dlarhs.$(o_ext) dlatb4.$(o_ext) dlatb5.$(o_ext) dlattb.$(o_ext) dlattp.$(o_ext) \
   dlattr.$(o_ext) dlavsp.$(o_ext) dlavsy.$(o_ext) dlqt01.$(o_ext) dlqt02.$(o_ext) \
   dlqt03.$(o_ext) dpbt01.$(o_ext) dpbt02.$(o_ext) dpbt05.$(o_ext) dpot01.$(o_ext) \
   dpot02.$(o_ext) dpot03.$(o_ext) dpot05.$(o_ext) dpst01.$(o_ext) dppt01.$(o_ext) \
   dppt02.$(o_ext) dppt03.$(o_ext) dppt05.$(o_ext) dptt01.$(o_ext) dptt02.$(o_ext) \
   dptt05.$(o_ext) dqlt01.$(o_ext) dqlt02.$(o_ext) dqlt03.$(o_ext) dqpt01.$(o_ext) \
   dqrt01.$(o_ext) dqrt02.$(o_ext) dqrt03.$(o_ext) dqrt11.$(o_ext) dqrt12.$(o_ext) \
   dqrt13.$(o_ext) dqrt14.$(o_ext) dqrt15.$(o_ext) dqrt16.$(o_ext) dqrt17.$(o_ext) \
   drqt01.$(o_ext) drqt02.$(o_ext) drqt03.$(o_ext) drzt01.$(o_ext) drzt02.$(o_ext) \
   dspt01.$(o_ext) dsyt01.$(o_ext) \
   dtbt02.$(o_ext) dtbt03.$(o_ext) dtbt05.$(o_ext) dtbt06.$(o_ext) dtpt01.$(o_ext) \
   dtpt02.$(o_ext) dtpt03.$(o_ext) dtpt05.$(o_ext) dtpt06.$(o_ext) dtrt01.$(o_ext) \
   dtrt02.$(o_ext) dtrt03.$(o_ext) dtrt05.$(o_ext) dtrt06.$(o_ext) \
   dtzt01.$(o_ext) dtzt02.$(o_ext) dgennd.$(o_ext)

DLINTST += derrvx.$(o_ext) ddrvge.$(o_ext) ddrvgb.$(o_ext) derrge.$(o_ext) ddrvpo.$(o_ext) derrpo.$(o_ext)

ZLINTST = zchkaa.$(o_ext) \
   zchkeq.$(o_ext) zchkgb.$(o_ext) zchkge.$(o_ext) zchkgt.$(o_ext) \
   zchklq.$(o_ext) zchkpb.$(o_ext) \
   zchkpo.$(o_ext) zchkps.$(o_ext) zchkpp.$(o_ext) zchkpt.$(o_ext) zchkq3.$(o_ext) zchkql.$(o_ext) zchkqp.$(o_ext) \
   zchkqr.$(o_ext) zchkrq.$(o_ext) zchktb.$(o_ext) \
   zchktp.$(o_ext) zchktr.$(o_ext) zchktz.$(o_ext) \
   zdrvgt.$(o_ext) zdrvhp.$(o_ext) \
   zdrvls.$(o_ext) zdrvpb.$(o_ext) zdrvpp.$(o_ext) zdrvpt.$(o_ext) \
   zdrvsp.$(o_ext) \
   zerrgt.$(o_ext) zerrlq.$(o_ext) \
   zerrls.$(o_ext) zerrps.$(o_ext) zerrql.$(o_ext) zerrqp.$(o_ext) \
   zerrqr.$(o_ext) zerrrq.$(o_ext) zerrtr.$(o_ext) zerrtz.$(o_ext) \
   zgbt01.$(o_ext) zgbt02.$(o_ext) zgbt05.$(o_ext) zgelqs.$(o_ext) zgeqls.$(o_ext) zgeqrs.$(o_ext) \
   zgerqs.$(o_ext) zget01.$(o_ext) zget02.$(o_ext) \
   zget03.$(o_ext) zget04.$(o_ext) zget07.$(o_ext) zgtt01.$(o_ext) zgtt02.$(o_ext) \
   zgtt05.$(o_ext) zhet01.$(o_ext) zhpt01.$(o_ext) zlaipd.$(o_ext) zlaptm.$(o_ext) zlarhs.$(o_ext) zlatb4.$(o_ext) zlatb5.$(o_ext) \
   zlatsp.$(o_ext) zlatsy.$(o_ext) zlattb.$(o_ext) zlattp.$(o_ext) zlattr.$(o_ext) \
   zlavhe.$(o_ext) zlavhp.$(o_ext) zlavsp.$(o_ext) zlavsy.$(o_ext) zlqt01.$(o_ext) \
   zlqt02.$(o_ext) zlqt03.$(o_ext) zpbt01.$(o_ext) zpbt02.$(o_ext) zpbt05.$(o_ext) \
   zpot01.$(o_ext) zpot02.$(o_ext) zpot03.$(o_ext) zpot05.$(o_ext) zpst01.$(o_ext) \
   zppt01.$(o_ext) zppt02.$(o_ext) zppt03.$(o_ext) zppt05.$(o_ext) zptt01.$(o_ext) \
   zptt02.$(o_ext) zptt05.$(o_ext) zqlt01.$(o_ext) zqlt02.$(o_ext) zqlt03.$(o_ext) \
   zqpt01.$(o_ext) zqrt01.$(o_ext) zqrt02.$(o_ext) zqrt03.$(o_ext) zqrt11.$(o_ext) \
   zqrt12.$(o_ext) zqrt13.$(o_ext) zqrt14.$(o_ext) zqrt15.$(o_ext) zqrt16.$(o_ext) \
   zqrt17.$(o_ext) zrqt01.$(o_ext) zrqt02.$(o_ext) zrqt03.$(o_ext) zrzt01.$(o_ext) zrzt02.$(o_ext) \
   zsbmv.$(o_ext)  zspt01.$(o_ext) \
   zspt02.$(o_ext) zspt03.$(o_ext) zsyt01.$(o_ext) zsyt02.$(o_ext) zsyt03.$(o_ext) \
   ztbt02.$(o_ext) ztbt03.$(o_ext) ztbt05.$(o_ext) ztbt06.$(o_ext) ztpt01.$(o_ext) \
   ztpt02.$(o_ext) ztpt03.$(o_ext) ztpt05.$(o_ext) ztpt06.$(o_ext) ztrt01.$(o_ext) \
   ztrt02.$(o_ext) ztrt03.$(o_ext) ztrt05.$(o_ext) ztrt06.$(o_ext) \
   ztzt01.$(o_ext) ztzt02.$(o_ext) dget06.$(o_ext) zgennd.$(o_ext)

ZLINTST += zerrvx.$(o_ext) zdrvge.$(o_ext) zdrvgb.$(o_ext) zerrge.$(o_ext) zdrvpo.$(o_ext) \
	zerrpo.$(o_ext)

DSLINTST = dchkab.$(o_ext) \
	ddrvab.$(o_ext) ddrvac.$(o_ext) derrab.$(o_ext) derrac.$(o_ext) dget08.$(o_ext)          \
	alaerh.$(o_ext) alahd.$(o_ext)  aladhd.$(o_ext) alareq.$(o_ext) \
	chkxer.$(o_ext) dlarhs.$(o_ext) dlatb4.$(o_ext) xerbla.$(o_ext) \
	dget02.$(o_ext) dpot06.$(o_ext)

ZCLINTST = zchkab.$(o_ext) \
	zdrvab.$(o_ext) zdrvac.$(o_ext) zerrab.$(o_ext) zerrac.$(o_ext) zget08.$(o_ext)          \
	alaerh.$(o_ext) alahd.$(o_ext)  aladhd.$(o_ext) alareq.$(o_ext) \
	chkxer.$(o_ext) zget02.$(o_ext) zlarhs.$(o_ext) zlatb4.$(o_ext) \
	zsbmv.$(o_ext)  xerbla.$(o_ext) zpot06.$(o_ext) zlaipd.$(o_ext)

SLINTSTRFP = schkrfp.$(o_ext) sdrvrfp.$(o_ext) sdrvrf1.$(o_ext) sdrvrf2.$(o_ext) sdrvrf3.$(o_ext) sdrvrf4.$(o_ext) serrrfp.$(o_ext) \
	slatb4.$(o_ext) slarhs.$(o_ext) sget04.$(o_ext) spot01.$(o_ext) spot03.$(o_ext) spot02.$(o_ext) \
	chkxer.$(o_ext) xerbla.$(o_ext) alaerh.$(o_ext) aladhd.$(o_ext) alahd.$(o_ext) alasvm.$(o_ext)

DLINTSTRFP = dchkrfp.$(o_ext) ddrvrfp.$(o_ext) ddrvrf1.$(o_ext) ddrvrf2.$(o_ext) ddrvrf3.$(o_ext) ddrvrf4.$(o_ext) derrrfp.$(o_ext) \
	dlatb4.$(o_ext) dlarhs.$(o_ext) dget04.$(o_ext) dpot01.$(o_ext) dpot03.$(o_ext) dpot02.$(o_ext) \
	chkxer.$(o_ext) xerbla.$(o_ext) alaerh.$(o_ext) aladhd.$(o_ext) alahd.$(o_ext) alasvm.$(o_ext)

CLINTSTRFP = cchkrfp.$(o_ext) cdrvrfp.$(o_ext) cdrvrf1.$(o_ext) cdrvrf2.$(o_ext) cdrvrf3.$(o_ext) cdrvrf4.$(o_ext) cerrrfp.$(o_ext) \
	claipd.$(o_ext) clatb4.$(o_ext) clarhs.$(o_ext) csbmv.$(o_ext) cget04.$(o_ext) cpot01.$(o_ext) cpot03.$(o_ext) cpot02.$(o_ext) \
	chkxer.$(o_ext) xerbla.$(o_ext) alaerh.$(o_ext) aladhd.$(o_ext) alahd.$(o_ext) alasvm.$(o_ext)

ZLINTSTRFP = zchkrfp.$(o_ext) zdrvrfp.$(o_ext) zdrvrf1.$(o_ext) zdrvrf2.$(o_ext) zdrvrf3.$(o_ext) zdrvrf4.$(o_ext) zerrrfp.$(o_ext) \
	zlatb4.$(o_ext) zlaipd.$(o_ext) zlarhs.$(o_ext) zsbmv.$(o_ext) zget04.$(o_ext) zpot01.$(o_ext) zpot03.$(o_ext) zpot02.$(o_ext) \
	chkxer.$(o_ext) xerbla.$(o_ext) alaerh.$(o_ext) aladhd.$(o_ext) alahd.$(o_ext) alasvm.$(o_ext)

TMGLIB = testing/matgen/tmglib.a

$(cdir)/all: $(cdir)/single $(cdir)/double $(cdir)/complex $(cdir)/complex16 $(cdir)/liblapacktest.a

$(cdir)/single:    xlintsts
$(cdir)/double:    xlintstd
$(cdir)/complex:   xlintstc
$(cdir)/complex16: xlintstz

$(TMGLIB):
	cd testing/matgen && $(MAKE)

xlintsts : $(ALINTST) $(SLINTST) $(SCLNTST) testing/fortran.$(o_ext) $(TMGLIB)
	$(FORT) $(ALINTST) $(SCLNTST) $(SLINTST) \
	$(TMGLIB) -o xlintsts \
	testing/fortran.$(o_ext) \
	$(LDFLAGS) -L$(MAGMA_DIR)/lib -lmagma \
	$(LIBDIR) $(LIB)

xlintstc : $(ALINTST) $(CLINTST) $(SCLNTST) testing/fortran.$(o_ext) $(TMGLIB)
	$(FORT) $(ALINTST) $(SCLNTST) $(CLINTST) \
	$(TMGLIB) -o xlintstc \
	testing/fortran.$(o_ext) \
	$(LDFLAGS) -L$(MAGMA_DIR)/lib -lmagma \
	$(LIBDIR) $(LIB)
 
xlintstd : $(ALINTST) $(DLINTST) $(DZLNTST) testing/fortran.$(o_ext) $(TMGLIB)
	$(FORT) $(ALINTST) $(DLINTST) $(DZLNTST) \
	$(TMGLIB) -o xlintstd \
	testing/fortran.$(o_ext) \
	$(LDFLAGS) -L$(MAGMA_DIR)/lib -lmagma \
	$(LIBDIR) $(LIB)
 
xlintstz : $(ALINTST) $(ZLINTST) $(DZLNTST) testing/fortran.$(o_ext) $(TMGLIB)
	$(FORT) $(ALINTST) $(DZLNTST) $(ZLINTST) \
	$(TMGLIB) -o xlintstz \
	testing/fortran.$(o_ext) \
	$(LDFLAGS) -L$(MAGMA_DIR)/lib -lmagma \
	$(LIBDIR) $(LIB)
 
$(ALINTST): $(FRC)
$(SCLNTST): $(FRC)
$(DZLNTST): $(FRC)
$(SLINTST): $(FRC)
$(CLINTST): $(FRC)
$(DLINTST): $(FRC)
$(ZLINTST): $(FRC)

FRC:
	@FRC=$(FRC)
 
# $(cdir)/clean:
# 	rm -f *.$(o_ext) *.mod liblapacktest.a *~
# 
# $(cdir)/cleanall: $(cdir)/clean
# 	rm -f liblapacktest.a xlintsts xlintstd xlintstc xlintstz testing_results.txt


# ----------------------------------------------------------------------
# pop first directory
cdir      := $(firstword $(dir_stack))
dir_stack := $(wordlist 2, $(words $(dir_stack)), $(dir_stack))
