#!/usr/bin/perl -0777 -p
#
# Used as INPUT_FILTER in Doxyfile to strips out "Arguments" and "Purpose"
# from MAGMA docs, as doxygen provides its own sections.
#
# -0777 slurps whole files; see 'man perlrun'

s/^ +Arguments *\n +[-=]{2,}$/\n/gm;
s/^ +Purpose *\n +[-=]{2,}$/\n/gm;
